---
- name: Prepare publisher and hypervisor
  become: true
  hosts:
    - publisher
    - hypervisors
  tasks:
      - name: Disable kernel adresses exposition restriction
        shell:
          cmd: >-
            echo 0 > /proc/sys/kernel/kptr_restrict
      - name: Send ptp4l configuration file
        copy:
          src: ../files/configuration/ptp4l.conf
          dest: /etc/ptp4l.conf
        notify:
          Enable ptp4l.service
      - name: Send ptp4l.service
        template:
          src: ../files/templates/ptp4l.service.j2
          dest: /etc/systemd/system/ptp4l.service
        notify:
          Enable ptp4l.service
      - name: Send phc2sys.service
        template:
          src: ../files/templates/phc2sys.service.j2
          dest: /etc/systemd/system/phc2sys.service
        notify:
          Enable phc2sys.service
  handlers:
      - name: Enable ptp4l.service
        ansible.builtin.systemd:
          service: ptp4l.service
          enabled: true
          state: restarted
          daemon_reload: true
      - name: Enable phc2sys.service
        ansible.builtin.systemd:
          service: phc2sys.service
          enabled: true
          state: restarted
          daemon_reload: true

- name: Configure SV timestamp logger
  become: true
  hosts:
    - publisher
    - subscriber
  tasks:
      - name: Send SV timestamp logger
        copy:
          src: ../files/sv_timestamp_logger.tar
          dest: /tmp/sv_timestamp_logger.tar
      - name: Load SV timestamp logger
        command: docker image load -i /tmp/sv_timestamp_logger.tar

- name: Prepare vms
  become: true
  hosts:
    - subscriber
  tasks:
      - name: Disable kernel adresses exposition restriction
        shell:
          cmd: >-
            echo 0 > /proc/sys/kernel/kptr_restrict
      - name: Send phc2sys.service
        template:
          src: ../files/templates/vms_phc2sys.service.j2
          dest: /etc/systemd/system/phc2sys.service
        notify:
          - Enable phc2sys.service
  handlers:
      - name: Enable phc2sys.service
        ansible.builtin.systemd:
          service: phc2sys.service
          enabled: true
          state: restarted
          daemon_reload: true
