---
- name: Prepare receiver
  become: true
  vars:
    - first_SV: 1096
  hosts:
    - hypervisors
  tasks:
      - name: Send SV timestamp logger
        copy:
          src: ../files/sv_timestamp_logger.tar
          dest: /tmp/sv_timestamp_logger.tar
      - name: Load SV timestamp logger
        command: docker image load -i /tmp/sv_timestamp_logger.tar
      - name : Run SV timestamp logger container
        command:
          docker run --privileged \
          -d \
          -v /tmp:/tmp \
          --name sv_timestamp_logger \
          --network=host sv_timestamp_logger \
          -d {{sv_interface}} \
          -f /tmp/ts_sv_subscriber_{{ inventory_hostname }} \
          --first_SV_cnt \ {{first_SV}} \
           --max_SV_cnt 4000

- name: Prepare publisher
  become: true
  hosts:
    publisher
  vars:
    - pcap_file: Df_Tri_Z1
    - first_SV: 1096
  tasks:
      - name: Send SV timestamp logger
        copy:
          src: ../files/sv_timestamp_logger.tar
          dest: /tmp/sv_timestamp_logger.tar
      - name: Load SV timestamp logger
        command: docker image load -i /tmp/sv_timestamp_logger.tar
      - name : Run SV timestamp logger container
        command:
          docker run --privileged \
          -d \
          -v /tmp:/tmp \
          --name sv_timestamp_logger \
          --network=host sv_timestamp_logger \
          -d {{sv_interface}} \
          -f /tmp/ts_sv_publisher_{{ inventory_hostname }} \
          --first_SV_cnt \ {{first_SV}} \
           --max_SV_cnt 4000
      - name: Send SV
        command: chrt --fifo 1 bittwist -i {{ sv_interface }} /pcap/{{ pcap_file }}.pcap -l {{ pcap_cycle }}

- name: Stop test on receiver
  become: true
  hosts:
    - hypervisors
  tasks:
      - name: Stop SV timestamp logger
        command:
          docker stop sv_timestamp_logger
      - name: Retrieve results
        shell:
          cmd: >-
            docker logs sv_timestamp_logger > /tmp/sv_drops
      - name: Fetch sv drop
        fetch:
          src: /tmp/sv_drops
          dest: ../tests_results/
          flat: true
      - name: Fetch subscriber timestamps
        fetch:
          src: /tmp/ts_sv_subscriber_{{ inventory_hostname }}
          dest: ../tests_results/
          flat: true
      - name: Remove SV timestamp logger
        command:
          docker rm sv_timestamp_logger

- name: Stop test on publisher
  become: true
  hosts:
    - publisher
  tasks:
      - name: Stop SV timestamp logger
        command:
          docker stop sv_timestamp_logger
      - name: Compute results
        shell:
          cmd: >-
            docker logs sv_timestamp_logger > /tmp/sv_drops
      - name: Fetch sv drop
        fetch:
          src: /tmp/sv_drops
          dest: ../tests_results/
          flat: true
      - name: Remove SV timestamp logger
        command:
          docker rm sv_timestamp_logger
      - name: Fetch publisher timestamps
        fetch:
          src: /tmp/ts_sv_publisher_{{ inventory_hostname }}
          dest: ../tests_results/
          flat: true
- name: Compute results
  hosts:
    - localhost
  tasks:
    - name: Generate latency report
      command:
        python3 ../files/scripts/generate_latency_report.py -s ../tests_results/ts_sv_subscriber_adv -p ../tests_results/ts_sv_publisher_amd -o ../tests_results
