---
- name: Prepare receiver
  vars:
    - first_SV: 1096
  hosts:
    - vms
  tasks:
      - name: Send SV timestamp logger
        copy:
          src: ../files/sv_timestamp_logger.tar
          dest: /tmp/sv_timestamp_logger.tar
      - name: Load SV timestamp logger
        become: true
        command: docker image load -i /tmp/sv_timestamp_logger.tar
      - name : Run SV timestamp logger container
        become: true
        command:
          docker run --privileged \
          -d \
          -v /tmp:/tmp \
          --name sv_timestamp_logger \
          --network=host sv_timestamp_logger \
          -d {{sv_interface}} \
          -f /tmp/ts_sv_subscriber_{{ inventory_hostname }} \
          --first_SV_cnt \ {{first_SV}} \
           --max_SV_cnt 4000

- name: Prepare publisher
  hosts:
    publisher
  vars:
    - pcap_file: Df_Tri_Z1
    - first_SV: 1096
    - pcap_cycles: 10
  tasks:
      - name: Send SV timestamp logger
        copy:
          src: ../files/sv_timestamp_logger.tar
          dest: /tmp/sv_timestamp_logger.tar
      - name: Load SV timestamp logger
        become: true
        command: docker image load -i /tmp/sv_timestamp_logger.tar
      - name : Run SV timestamp logger container
        become: true
        command:
          docker run --privileged \
          -d \
          -v /tmp:/tmp \
          --name sv_timestamp_logger \
          --network=host sv_timestamp_logger \
          -d {{sv_interface}} \
          -f /tmp/ts_sv_publisher_{{ inventory_hostname }} \
          --first_SV_cnt \ {{first_SV}} \
           --max_SV_cnt 4000
      - name: Send SV
        command: bittwist -i {{ sv_interface }} /pcap/{{ pcap_file }}.pcap -l {{ pcap_cycles }}

- name: Stop test on receiver
  hosts:
    - vms
  tasks:
      - name: Stop SV timestamp logger
        become: true
        command:
          docker stop sv_timestamp_logger
      - name: Retrieve results
        become: true
        shell:
          cmd: >-
            docker logs sv_timestamp_logger > /tmp/sv_drops
      - name: Fetch sv drop
        become: true
        fetch:
          src: /tmp/sv_drops
          dest: ../tests_results/
          flat: true
      - name: Fetch subscriber timestamps
        become: true
        fetch:
          src: /tmp/ts_sv_subscriber_{{ inventory_hostname }}
          dest: ../tests_results/
          flat: true
      - name: Remove SV timestamp logger
        become: true
        command:
          docker rm sv_timestamp_logger

- name: Stop test on publisher
  hosts:
    - publisher
  tasks:
      - name: Stop SV timestamp logger
        become: true
        command:
          docker stop sv_timestamp_logger
      - name: Compute results
        become: true
        shell:
          cmd: >-
            docker logs sv_timestamp_logger > /tmp/sv_drops
      - name: Fetch sv drop
        become: true
        fetch:
          src: /tmp/sv_drops
          dest: ../tests_results/
          flat: true
      - name: Remove SV timestamp logger
        become: true
        command:
          docker rm sv_timestamp_logger
      - name: Fetch publisher timestamps
        become: true
        fetch:
          src: /tmp/ts_sv_publisher_{{ inventory_hostname }}
          dest: ../tests_results/
          flat: true
- name: Compute results
  hosts:
    - localhost
  tasks:
    - name: Generate latency report
      command:
        python3 ../files/scripts/generate_latency_report.py -s ../tests_results/ts_sv_subscriber_debian-paul -p ../tests_results/ts_sv_publisher_amd -o ../tests_results
